/**********************************************************************************************
@Description: An apex page controller that takes the user to the right start page based on credentials or lack thereof
----------------------------------------------------------------------------------------------
Version Date(DD-MM-YYYY)    Author              Version History
-----------------------------------------------------------------------------------------------
1.1     11-01-2022          Microgrid           Initial Draft
***********************************************************************************************/
public with sharing class CommunitiesSelfRegConfirmController {
    
    public CommunitiesSelfRegConfirmController() {}
}