/**********************************************************************************************
@Description: An apex Class will provide all constant values
----------------------------------------------------------------------------------------------
Version Date(DD-MM-YYYY)    Author              Version History
-----------------------------------------------------------------------------------------------
1.1     11-01-2022          Microgrid           Initial Draft
***********************************************************************************************/
public class ZOE_Constant {
    public static String STR_CALENDAR = 'CALENDAR';
    public static String STR_LABTRACKER = 'LABTRACKER';
    public static String  USER_PROFESSION_NEUROLOGIST = 'NEUROLOGIST';
    public static String  USER_PROFESSION_NEUROPEDIATRICIANS = 'NEUROPEDIATRICIAN';
    public static String  USER_PROFESSION_PEDIATRICIAN = 'PEDIATRICIAN';
    public static String  USER_PROFESSION_PHARMACIST = 'PHARMACIST';
    public static String  USER_PROFESSION_OTHER = 'OTHER';
    public static String  USER_PROFESSION_NURSE = 'NURSE';
    public static String  USER_PROFESSION_PHARMA_TECHNICIAN = 'PHARMATECHNICIAN';
    public static String  USER_ROLE_PHARMACIST = 'PHARMACIST';
    public static String  USER_ROLE_HCP = 'HCP';
    public static String  USER_ROLE_FULLACCESS = 'NOVARTIES FULL ACCESS';
    public static String  USER_ROLE_TEST = 'Test';
    public static String  USER_ROLE_NURSE= 'NURSE';
    public static String  STR_EN_US = 'en_US';
    public static String  STR_UTF = 'UTF-8';
    public static String  MC_INFUSION_CENTERS = 'Infusion Center Master';
    public static String  MC_Z_KIT='Z-Kit Calculator';
    public static String  MC_TRAINING='Training';
    public static String  MC_INSTITUTIONS='Institution Master';
    public static String  PENDING='Pending';
    public static String  APPROVED='Approved';
    public static String  SUCCESS='Success';
    public static String  REJECTED='Rejected';
    public static String  REGISTERED='Registered';
    public static String  VIRTUAL_ASISTENT='Virtual Asistente';
    public static String  META_ZOE='ZOE';
    public static String  COMMUNITY = 'Community';
}